[package]
name = "envuse-parser"
version = "0.1.0-beta.0"
edition = "2021"

[lib]
doc = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
